default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.2
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        files: ^src/.*\.(c|h)pp$
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.2
    hooks:
      - id: cpplint
        stages: ["pre-push"]
        files: ^src/.*\.(c|h)pp$
        args: ["--repository=include", "--extensions=cpp,hpp"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        stages: ["pre-push"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
        types: [python]
        exclude: ^(?:build_tools|etc)/
        require_serial: true
        stages: [pre-push]
