#!/usr/bin/env python3
# Distributed under the terms of the GPL license version 3.
# The full license is in the file LICENSE, distributed with this software.
# AI assistance: OpenAI Codex helped implement and test this generator.

r"""Generate draft stubs from the built package, source annotations, and docstrings.

Run in an environment containing the built extension, for example::

    uv run --no-sync --with pybind11-stubgen==2.5.5 python etc/generate-stubs.py \
        libsemigroups_pybind11.action
    uv run --no-sync --with pybind11-stubgen==2.5.5 python etc/generate-stubs.py \
        libsemigroups_pybind11.sims --output-dir _generate/stubs

The module argument is required. A single stub is printed to stdout by default,
with diagnostics on standard error. Use --output-dir to write files instead.
Package targets include the submodules discovered by pybind11-stubgen and need
--output-dir when generating multiple stubs. Existing files require --force.
Extension targets default to the classes exported by the public package and its
public submodules, together with their typing dependencies. Use --no-public-only
to generate the full extension stub.
Use --strict to stop on pybind11-stubgen diagnostics instead of emitting drafts.
Output is a draft: missing annotations, dynamic dispatch, and C++ conversions
still require review. This script does not install dependencies or add py.typed.
"""

from __future__ import annotations

import argparse
import ast
import builtins
import contextlib
import copy
import enum
import importlib
import importlib.util
import inspect
import json
import keyword
import re
import subprocess
import sys
import tempfile
import types
import typing
from pathlib import Path

EXTENSION_MODULE = "_libsemigroups_pybind11"

HEADER = """# Generated by etc/generate-stubs.py using pybind11-stubgen.
# Draft only: review signatures and incomplete types before publishing.
# AI assistance: OpenAI Codex helped implement the generator.

"""


def expression(text: str) -> ast.expr:
    """Parse a type expression without executing it."""
    return ast.parse(text, mode="eval").body


def parse_stub(text: str, module_name: str, *, strict: bool) -> ast.Module:
    """Handle native names that cannot be written in Python stub syntax."""
    lines = text.splitlines(keepends=True)
    renamed = {}
    while True:
        try:
            tree = ast.parse("".join(lines))
        except SyntaxError as error:
            if strict or error.lineno is None:
                raise
            index = error.lineno - 1
            match = re.fullmatch(r"(\s*class \w+)\((.+)\):\s*", lines[index])
            if match is None:
                # A binding can accept a keyword named "from", but Python syntax cannot.
                line = lines[index]
                offset = (error.offset or 1) - 1
                name = re.match(r"(\w+)(?=\s*[:=,)])", line[offset:])
                if (
                    line.lstrip().startswith("def ")
                    and line[:offset].rstrip().endswith(("(", ","))
                    and name
                    and keyword.iskeyword(name[1])
                ):
                    replacement = name[1] + "_"
                    lines[index] = line[:offset] + replacement + line[offset + len(name[1]) :]
                    renamed.setdefault(error.lineno, set()).add(replacement)
                    print(
                        f"{module_name}: representing keyword parameter {name[1]!r} "
                        f"as positional-only {replacement!r}",
                        file=sys.stderr,
                    )
                    continue
                raise
            try:
                expression(match[2])
            except SyntaxError:
                # Some extension types have names such as detail::CongruenceCommon.
                # Any records the unknown base without inventing a Python class.
                print(
                    f"{module_name}: replacing invalid base {match[2]!r} with typing.Any",
                    file=sys.stderr,
                )
                lines[index] = f"{match[1]}(typing.Any):\n"
            else:
                raise error
        else:
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef) and node.lineno in renamed:
                    names = renamed[node.lineno]
                    if any(arg.arg in names for arg in node.args.kwonlyargs):
                        raise SyntaxError(
                            "Cannot represent a keyword-only parameter named after a keyword"
                        )
                    count = max(
                        (i + 1 for i, arg in enumerate(node.args.args) if arg.arg in names),
                        default=0,
                    )
                    node.args.posonlyargs += node.args.args[:count]
                    node.args.args = node.args.args[count:]
            return tree


def documented_signatures(name: str, doc: str) -> list[ast.FunctionDef]:
    """Prefer project signature overrides, then pybind11 signature lines."""
    overrides = re.findall(r"^\s*:sig=[^(\n]*(\(.*):\s*$", doc, re.MULTILINE)
    signatures = overrides or re.findall(
        rf"^\s*(?:\d+\. )?{re.escape(name)}(\(.*)$", doc, re.MULTILINE
    )
    result = []
    seen = set()
    for signature in signatures:
        try:
            node = ast.parse(f"def {name}{signature}: ...").body[0]
        except SyntaxError:
            continue  # C++ spellings and enum defaults need manual review.
        key = ast.dump(node)
        if key not in seen and not (node.args.vararg and node.args.kwarg and not node.args.args):
            result.append(typing.cast(ast.FunctionDef, node))
            seen.add(key)
    return result


def bindings(nodes: list[ast.stmt]) -> set[str]:
    """Collect names bound at module scope, including imported aliases."""
    names = set()
    for node in nodes:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for alias in node.names:
                names.add(alias.asname or alias.name.split(".")[0])
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names.add(node.target.id)
        elif isinstance(node, ast.Assign):
            names.update(target.id for target in node.targets if isinstance(target, ast.Name))
    return names


def public_native_classes(public: types.ModuleType, native: types.ModuleType) -> set[str]:
    """Find native classes by identity, following the public modules' exports."""
    exported_ids = set()
    pending = [public]
    seen = set()
    while pending:
        module = pending.pop()
        if id(module) in seen:
            continue
        seen.add(id(module))
        names = getattr(
            module, "__all__", [name for name in vars(module) if not name.startswith("_")]
        )
        for name in names:
            value = getattr(module, name, None)
            if inspect.isclass(value):
                exported_ids.add(id(value))
            elif inspect.ismodule(value) and value.__name__.startswith(public.__name__ + "."):
                pending.append(value)
    return {
        name
        for name, value in vars(native).items()
        if inspect.isclass(value) and id(value) in exported_ids
    }


def native_dependencies(tree: ast.Module, native: types.ModuleType) -> set[str]:
    """Find native names used by bases, annotations, aliases, and default values."""
    names = set()
    pending = [tree]
    for node in ast.walk(tree):
        annotation = None
        if isinstance(node, (ast.arg, ast.AnnAssign)):
            annotation = node.annotation
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            annotation = node.returns
        if annotation is not None:
            # Forward references inside annotations can also name native types.
            for part in ast.walk(annotation):
                if isinstance(part, ast.Constant) and isinstance(part.value, str):
                    with contextlib.suppress(SyntaxError):
                        pending.append(expression(part.value))
    for root in pending:
        for node in ast.walk(root):
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                names.add(node.id)
            elif isinstance(node, ast.Attribute):
                parts = ast.unparse(node).split(".")
                if parts[0] == native.__name__ and len(parts) > 1:
                    names.add(parts[1])
            elif isinstance(node, ast.ImportFrom) and node.module == native.__name__:
                names.update(alias.name for alias in node.names)
    return {
        name
        for name in names
        if name in vars(native) and not name.startswith("__") and name.isidentifier()
    }


def generate_public_raw(module_name: str, names_json: str, output_dir: str, strict: bool) -> None:
    """Run in a subprocess so inspection cannot change the caller's imported modules."""
    import pybind11_stubgen

    native = importlib.import_module(module_name)
    selected = set(json.loads(names_json))
    roots = selected.copy()
    # dir() controls discovery; getattr() still resolves every real native name.
    # Importing the public package here would rename some native classes for Sphinx.
    view = types.ModuleType(module_name)
    vars(view).update(vars(native))
    view.__dir__ = lambda: sorted(selected)
    sys.modules[module_name] = view
    try:
        while True:
            command = [module_name, "-o", output_dir]
            if strict:
                command.append("--exit-code")
            pybind11_stubgen.main(command)
            path = Path(output_dir) / f"{module_name}.pyi"
            tree = parse_stub(path.read_text(encoding="utf-8"), module_name, strict=strict)
            dependencies = native_dependencies(tree, native) - selected
            if not dependencies:
                break
            selected.update(dependencies)
    finally:
        sys.modules[module_name] = native
    print(
        f"Selected {len(roots)} public native classes and {len(selected - roots)} supporting names."
    )
    if selected - roots:
        print("Supporting names: " + ", ".join(sorted(selected - roots)))


def accepts_integer_index(annotation: ast.expr | None) -> bool:
    """Identify integer overloads used by Python's implicit sequence iteration."""
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return accepts_integer_index(annotation.left) or accepts_integer_index(annotation.right)
    return isinstance(annotation, (ast.Name, ast.Attribute)) and ast.unparse(annotation).split(".")[
        -1
    ] in {"int", "SupportsInt", "SupportsIndex"}


class TypeNames(ast.NodeTransformer):
    """Resolve documentation names in the public package and the owning class."""

    def __init__(self, refiner: Refiner, parameters: tuple, *, specialize: bool = True):
        self.refiner = refiner
        self.parameters = {param.__name__.lstrip("_"): param.__name__ for param in parameters}
        self.specialize = specialize

    def visit_Subscript(self, node: ast.Subscript) -> ast.Subscript:
        previous = self.specialize
        self.specialize = False
        node.value = self.visit(node.value)
        self.specialize = previous
        node.slice = self.visit(node.slice)
        return node

    def visit_Attribute(self, node: ast.Attribute) -> ast.expr:
        if ast.unparse(node) == "typing.Self":
            return expression("typing_extensions.Self")
        parts = ast.unparse(node).split(".")
        value = getattr(self.refiner.module, parts[0], None)
        if inspect.isclass(value):
            for part in parts[1:]:
                value = getattr(value, part, None)
            if inspect.isclass(value) and value.__module__ != self.refiner.module.__name__:
                self.refiner.imports.add(value.__module__)
                return expression(f"{value.__module__}.{value.__qualname__}")
        # Qualified names already supplied by pybind11-stubgen have imports.
        return node

    def visit_Name(self, node: ast.Name) -> ast.expr:
        name = node.id
        if name in self.parameters:
            return ast.Name(id=self.parameters[name], ctx=ast.Load())
        value = getattr(self.refiner.module, name, None)
        if inspect.isclass(value) and self.specialize and getattr(value, "__parameters__", ()):
            params = ", ".join(param.__name__ for param in value.__parameters__)
            return expression(f"{name}[{params}]")
        if name in self.refiner.names or hasattr(builtins, name):
            return node
        if name == "Self":
            return expression("typing_extensions.Self")
        if hasattr(typing, name):
            return expression(f"typing.{name}")
        value = getattr(self.refiner.public, name, None)
        if inspect.isclass(value):
            self.refiner.imports.add(value.__module__)
            return expression(f"{value.__module__}.{value.__qualname__}")
        self.refiner.incomplete.add(name)
        return expression("_typeshed.Incomplete")


class Refiner:
    """Combine runtime discovery with information lost by generic stub tools."""

    def __init__(self, module: types.ModuleType, tree: ast.Module, *, native_classes: bool = False):
        self.module = module
        self.native_classes = native_classes
        self.public = importlib.import_module("libsemigroups_pybind11")
        try:
            self.source = ast.parse(inspect.getsource(module))
        except (OSError, TypeError):
            self.source = ast.Module(body=[], type_ignores=[])
        self.names = bindings(tree.body) | bindings(self.source.body)
        self.imports = {"collections.abc", "datetime", "typing", "typing_extensions", "_typeshed"}
        if native_classes:
            self.imports.add(module.__name__)
        self.incomplete: set[str] = set()

    def annotation(self, node: ast.expr | None, parameters: tuple) -> ast.expr | None:
        if node is None:
            return None
        return TypeNames(self, parameters).visit(copy.deepcopy(node))

    def function(self, node: ast.FunctionDef, parameters: tuple) -> ast.FunctionDef:
        node = copy.deepcopy(node)
        args = node.args
        for arg in [*args.posonlyargs, *args.args, *args.kwonlyargs, args.vararg, args.kwarg]:
            if arg is not None:
                arg.annotation = self.annotation(arg.annotation, parameters)
                if arg.arg in {"self", "cls"}:
                    arg.annotation = None
        node.returns = self.annotation(node.returns, parameters)
        node.decorator_list = [
            dec
            for dec in node.decorator_list
            if ast.unparse(dec).split(".")[-1]
            in {"overload", "staticmethod", "classmethod", "property", "setter", "abstractmethod"}
        ]
        node.body = [ast.Expr(value=ast.Constant(value=Ellipsis))]
        return node

    def dispatch_annotations(self, owner: object, source: ast.FunctionDef) -> dict[str, ast.expr]:
        """Recognize class-valued constructor keywords used directly in dispatch keys."""
        mapping = getattr(owner, "_py_template_params_to_cxx_type", {})
        result = {}
        if source.name != "__init__" or not isinstance(mapping, dict) or not mapping:
            return result
        for node in ast.walk(source):
            if not (
                isinstance(node, ast.Assign)
                and isinstance(node.value, ast.Tuple)
                and any(
                    isinstance(target, ast.Attribute) and target.attr == "py_template_params"
                    for target in node.targets
                )
            ):
                continue
            for index, item in enumerate(node.value.elts):
                if not isinstance(item, ast.Name):
                    continue
                if not all(isinstance(key, tuple) and len(key) > index for key in mapping):
                    continue
                values = {key[index] for key in mapping}
                if not all(inspect.isclass(value) for value in values):
                    continue
                for value in values:
                    self.imports.add(value.__module__)
                result[item.id] = expression(
                    " | ".join(
                        sorted(f"type[{value.__module__}.{value.__qualname__}]" for value in values)
                    )
                )
        return result

    def functions(
        self,
        node: ast.FunctionDef,
        obj: object,
        source: ast.FunctionDef | None,
        parameters: tuple,
        owner: object,
    ) -> list[ast.FunctionDef]:
        doc = inspect.getdoc(obj) or ""
        documented = (
            documented_signatures(node.name, doc) if isinstance(obj, types.FunctionType) else []
        )
        if source is not None:
            result = copy.deepcopy(source)
            # Preserve actual parameter kinds/defaults; fill only missing annotations.
            if documented:
                candidates = {
                    arg.arg: arg.annotation
                    for sig in documented
                    for arg in [*sig.args.posonlyargs, *sig.args.args, *sig.args.kwonlyargs]
                }
                candidates.update(self.dispatch_annotations(owner, source))
                positional = [*result.args.posonlyargs, *result.args.args]
                defaults = [None] * (
                    len(positional) - len(result.args.defaults)
                ) + result.args.defaults
                for arg, default in zip(
                    [*positional, *result.args.kwonlyargs],
                    [*defaults, *result.args.kw_defaults],
                    strict=True,
                ):
                    if arg.annotation is None and candidates.get(arg.arg) is not None:
                        arg.annotation = copy.deepcopy(candidates[arg.arg])
                        if isinstance(default, ast.Constant) and default.value is None:
                            arg.annotation = expression(f"{ast.unparse(arg.annotation)} | None")
                if result.returns is None and len(documented) == 1:
                    result.returns = documented[0].returns
            return [self.function(result, parameters)]
        if not documented:
            return [self.function(node, parameters)]
        try:
            actual = inspect.signature(obj, follow_wrapped=False)
        except (TypeError, ValueError):
            actual = None
        for sig in documented:
            if (
                isinstance(sig.returns, ast.Name)
                and sig.returns.id == getattr(owner, "__name__", None)
                and re.search(r":returns?:\s*\*self\*", doc)
            ):
                sig.returns = expression("typing_extensions.Self")
            # CxxWrapper's forwarding closure accepts *args, without **kwargs.
            if (
                actual
                and any(p.kind == p.VAR_POSITIONAL for p in actual.parameters.values())
                and not any(p.kind == p.VAR_KEYWORD for p in actual.parameters.values())
            ):
                sig.args.posonlyargs += sig.args.args
                sig.args.args = []
            if len(documented) > 1:
                sig.decorator_list = [expression("typing.overload")]
        return [self.function(sig, parameters) for sig in documented]

    def scope(
        self, body: list[ast.stmt], owner: object, source: list[ast.stmt], parameters: tuple = ()
    ) -> list[ast.stmt]:
        definitions = {
            node.name: node for node in source if isinstance(node, (ast.ClassDef, ast.FunctionDef))
        }
        result = []
        rebuilt = set()
        for node in body:
            if (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and inspect.isclass(owner)
                and issubclass(owner, enum.Enum)
                and node.target.id in owner.__members__
            ):
                # Enum members in stubs are assignments, not annotated attributes.
                original = next(
                    (
                        item
                        for item in source
                        if isinstance(item, ast.Assign)
                        and any(
                            isinstance(target, ast.Name) and target.id == node.target.id
                            for target in item.targets
                        )
                    ),
                    None,
                )
                result.append(
                    copy.deepcopy(original)
                    if original is not None
                    else ast.Assign(targets=[node.target], value=ast.Constant(value=Ellipsis))
                )
                continue
            if (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and (
                    (node.target.id.startswith("_") and not node.target.id.endswith("__"))
                    or node.target.id in {"__orig_bases__", "__parameters__"}
                )
                and not isinstance(owner, types.ModuleType)
            ):
                continue
            if (
                isinstance(node, ast.Expr)
                and isinstance(node.value, ast.Constant)
                and isinstance(node.value.value, str)
            ):
                continue
            if isinstance(node, ast.ClassDef):
                cls = getattr(owner, node.name, None)
                if (
                    inspect.isclass(cls)
                    and cls.__module__ != self.module.__name__
                    and not self.native_classes
                ):
                    self.imports.add(cls.__module__)
                    result.append(
                        ast.parse(f"{node.name} = {cls.__module__}.{cls.__qualname__}").body[0]
                    )
                    continue
                original = definitions.get(node.name)
                class_source = original.body if isinstance(original, ast.ClassDef) else []
                if isinstance(original, ast.ClassDef):
                    node.bases = copy.deepcopy(original.bases)
                node.body = self.scope(
                    node.body, cls, class_source, getattr(cls, "__parameters__", ())
                )
                if cls is not None and "__getitem__" in vars(cls) and not hasattr(cls, "__iter__"):
                    getitem = next(
                        (
                            item
                            for item in node.body
                            if isinstance(item, ast.FunctionDef)
                            and item.name == "__getitem__"
                            and len(args := [*item.args.posonlyargs, *item.args.args]) == 2
                            and accepts_integer_index(args[1].annotation)
                        ),
                        None,
                    )
                    if getitem and getitem.returns:
                        node.body.append(
                            ast.parse(
                                "@typing.type_check_only\n"
                                "def __iter__(self) -> collections.abc.Iterator["
                                + ast.unparse(getitem.returns)
                                + "]: ..."
                            ).body[0]
                        )
                result.append(node)
            elif isinstance(node, ast.FunctionDef):
                if node.name in rebuilt:
                    continue
                obj = getattr(owner, node.name, None)
                if isinstance(obj, property):
                    accessors = [
                        item
                        for item in source
                        if isinstance(item, ast.FunctionDef) and item.name == node.name
                    ]
                    if accessors:
                        result.extend(self.function(item, parameters) for item in accessors)
                        rebuilt.add(node.name)
                        continue
                original = definitions.get(node.name)
                original = original if isinstance(original, ast.FunctionDef) else None
                functions = self.functions(node, obj, original, parameters, owner)
                if original or (
                    isinstance(obj, types.FunctionType)
                    and documented_signatures(node.name, inspect.getdoc(obj) or "")
                ):
                    rebuilt.add(node.name)
                result.extend(functions)
            else:
                result.append(node)
        return result

    def refine(self, tree: ast.Module) -> str:
        tree.body = self.scope(tree.body, self.module, self.source.body)
        source_imports = [
            node for node in self.source.body if isinstance(node, (ast.Import, ast.ImportFrom))
        ]
        imported_names = bindings(source_imports)
        typevars = {
            node.targets[0].id: node
            for node in self.source.body
            if isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and isinstance(getattr(self.module, node.targets[0].id, None), typing.TypeVar)
        }
        body = []
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and node.name in imported_names:
                # Preserve source re-exports even when __module__ was changed for Sphinx.
                continue
            if (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and (node.target.id in imported_names or node.target.id in typevars)
            ):
                continue
            if isinstance(node, (ast.Import, ast.ImportFrom)):
                node.names = [
                    alias
                    for alias in node.names
                    if (alias.asname or alias.name.split(".")[0]) not in imported_names
                ]
                if not node.names:
                    continue
            body.append(node)
        imports = [
            *source_imports,
            *[node for node in body if isinstance(node, (ast.Import, ast.ImportFrom))],
        ]
        imports += [ast.Import(names=[ast.alias(name=name)]) for name in sorted(self.imports)]
        # Future imports must come first; deduplicate imports from both sources.
        unique_imports = {ast.unparse(node): node for node in imports}
        tree.body = [
            unique_imports[key]
            for key in sorted(
                unique_imports, key=lambda key: (not key.startswith("from __future__"), key)
            )
        ]
        tree.body += list(typevars.values())
        tree.body += [node for node in body if not isinstance(node, (ast.Import, ast.ImportFrom))]
        exports = set(getattr(self.module, "__all__", ()))
        for node in tree.body:
            if (
                isinstance(node, ast.AnnAssign)
                and isinstance(node.target, ast.Name)
                and node.target.id == "__all__"
                and isinstance(node.value, (ast.List, ast.Tuple))
            ):
                exports.update(ast.literal_eval(node.value))
        used = {
            node.id
            for node in ast.walk(tree)
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load)
        } | exports
        cleaned = []
        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)) and not (
                isinstance(node, ast.ImportFrom) and node.module == "__future__"
            ):
                node.names = [
                    alias
                    for alias in node.names
                    if (alias.asname or alias.name.split(".")[0]) in used or alias.name == "*"
                ]
                if not node.names:
                    continue
            cleaned.append(node)
        tree.body = cleaned
        text = HEADER + ast.unparse(ast.fix_missing_locations(tree)) + "\n"
        text = re.sub(r"(\n[ \t]*(?:async )?def [^\n]+:)\n[ \t]+\.\.\.", r"\1 ...", text)
        ast.parse(text, feature_version=(3, 10))
        return text


def render_stubs(
    module_name: str, *, strict: bool = False, public_only: bool = False
) -> dict[Path, str]:
    """Generate validated drafts in memory, keyed by their relative module paths."""
    if public_only and module_name != EXTENSION_MODULE:
        raise ValueError(f"--public-only requires the {EXTENSION_MODULE} module")
    if importlib.util.find_spec("pybind11_stubgen") is None:
        raise RuntimeError(
            "Missing pybind11-stubgen. Run with: uv run --no-sync "
            f"--with pybind11-stubgen==2.5.5 python etc/generate-stubs.py {module_name}"
        )
    with tempfile.TemporaryDirectory(prefix="libsemigroups-stubs-") as temp:
        command = [sys.executable, "-m", "pybind11_stubgen", module_name, "-o", temp]
        if public_only:
            native = importlib.import_module(module_name)
            public = importlib.import_module("libsemigroups_pybind11")
            names = public_native_classes(public, native)
            if not names:
                raise RuntimeError("No publicly exported native classes found")
            command = [
                sys.executable,
                "-c",
                "import runpy, sys; "
                "runpy.run_path(sys.argv[1])['generate_public_raw']("
                "sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5] == '1')",
                str(Path(__file__).resolve()),
                module_name,
                json.dumps(sorted(names)),
                temp,
                "1" if strict else "0",
            ]
        elif strict:
            command.append("--exit-code")
        subprocess.run(command, check=True, stdout=sys.stderr)
        drafts = {}
        for path in sorted(Path(temp).rglob("*.pyi")):
            relative = path.relative_to(temp)
            parts = list(relative.with_suffix("").parts)
            if parts[-1] == "__init__":
                parts.pop()
            module = importlib.import_module(".".join(parts))
            tree = parse_stub(path.read_text(encoding="utf-8"), module.__name__, strict=strict)
            if public_only:
                tree.body = [node for node in tree.body if "__all__" not in bindings([node])]
                # This deliberately partial native stub leaves omitted objects untyped.
                tree.body += ast.parse(
                    "def __getattr__(name: str) -> _typeshed.Incomplete: ..."
                ).body
            refiner = Refiner(module, tree, native_classes=public_only)
            drafts[relative] = refiner.refine(tree)
            if refiner.incomplete:
                print(
                    f"{module.__name__}: unresolved documentation types: "
                    + ", ".join(sorted(refiner.incomplete)),
                    file=sys.stderr,
                )
        if not drafts:
            raise RuntimeError(f"No stubs generated for {module_name}")
        return drafts


def generate(
    module_name: str,
    output_dir: Path,
    *,
    force: bool = False,
    strict: bool = False,
    public_only: bool = False,
) -> list[Path]:
    """Generate and validate drafts before writing any destination files."""
    drafts = {
        output_dir / relative: text
        for relative, text in render_stubs(
            module_name, strict=strict, public_only=public_only
        ).items()
    }
    conflicts = [str(path) for path in drafts if path.exists()]
    if conflicts and not force:
        raise FileExistsError(
            "Existing stubs would be overwritten (use --force): " + ", ".join(conflicts)
        )
    for path, text in drafts.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w" if force else "x", encoding="utf-8") as stream:
            stream.write(text)
    return list(drafts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("module", help="importable module or package to generate stubs for")
    parser.add_argument(
        "--public-only",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="select public native classes and dependencies (default for the extension)",
    )
    output = parser.add_mutually_exclusive_group()
    output.add_argument("-o", "--output-dir", type=Path, help="write stubs under this directory")
    output.add_argument(
        "--stdout", action="store_true", help="print one stub to standard output (default)"
    )
    parser.add_argument("--force", action="store_true", help="replace existing generated files")
    parser.add_argument(
        "--strict", action="store_true", help="stop on pybind11-stubgen diagnostics"
    )
    args = parser.parse_args()
    module_name = args.module
    public_only = args.public_only
    if public_only is None:
        public_only = module_name == EXTENSION_MODULE
    if public_only and module_name != EXTENSION_MODULE:
        parser.error(f"--public-only requires the {EXTENSION_MODULE} module")
    if args.output_dir is None and args.force:
        parser.error("--force requires --output-dir")
    try:
        if args.output_dir is None:
            with contextlib.redirect_stdout(sys.stderr):
                drafts = render_stubs(module_name, strict=args.strict, public_only=public_only)
            if len(drafts) != 1:
                raise RuntimeError(
                    f"Standard output requires exactly one stub, but {module_name} "
                    f"generated {len(drafts)}; "
                    "target an individual module or use --output-dir"
                )
            sys.stdout.write(next(iter(drafts.values())))
        else:
            for path in generate(
                module_name,
                args.output_dir,
                force=args.force,
                strict=args.strict,
                public_only=public_only,
            ):
                print(path)
    except (
        ImportError,
        RuntimeError,
        OSError,
        SyntaxError,
        subprocess.CalledProcessError,
    ) as error:
        print(f"Stub generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
