# Distributed under the terms of the GPL license version 3.
# The full license is in the file LICENSE, distributed with this software.
# AI assistance: OpenAI Codex drafted and checked this sample stub.

# Sample types for the public action module. This does not opt the package into
# installed typing support via py.typed; related extension types remain untyped.
# The type parameters track elements and points; supported combinations of
# element, point, function, and side are still checked at runtime by action.py.

from collections.abc import Callable, Iterator
from datetime import datetime, timedelta
from typing import ClassVar, Generic, TypeVar, overload, type_check_only

from typing_extensions import Self

from _libsemigroups_pybind11 import (
    Gabow as _Gabow,
    Reporter as _Reporter,
    Runner as _Runner,
    Undefined as _Undefined,
    WordGraph as _WordGraph,
    side as _side,
)

from .adapters import ImageLeftAction as _ImageLeftAction, ImageRightAction as _ImageRightAction

__all__ = ["Action", "LeftAction", "RightAction"]

_Element = TypeVar("_Element")
_Point = TypeVar("_Point")

class Action(Generic[_Element, _Point]):
    def __init__(
        self,
        *,
        generators: list[_Element] | None = None,
        seeds: list[_Point] | None = None,
        func: type[_ImageLeftAction] | type[_ImageRightAction] | None = None,
        side: _side | None = None,
    ) -> None: ...
    def __getitem__(self, i: int) -> _Point: ...
    # Python iterates via __getitem__; this method only models that for typing.
    @type_check_only
    def __iter__(self) -> Iterator[_Point]: ...
    def __len__(self) -> int: ...
    def __contains__(self, pt: _Point) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, that: object) -> bool: ...
    def __copy__(self) -> Action[_Element, _Point]: ...
    def generators(self) -> Iterator[_Element]: ...

    # Methods attached by copy_cxx_mem_fns accept positional arguments only.
    def add_generator(self, gen: _Element, /) -> Self: ...
    def add_seed(self, seed: _Point, /) -> Self: ...
    def apply(self, pt: _Point, x: _Element, /) -> _Point: ...
    @overload
    def cache_scc_multipliers(self) -> bool: ...
    @overload
    def cache_scc_multipliers(self, val: bool, /) -> Self: ...
    def copy(self) -> Action[_Element, _Point]: ...
    def current_size(self) -> int: ...
    def empty(self) -> bool: ...
    def init(self) -> Self: ...
    def multiplier_from_scc_root(self, pos: int, /) -> _Element: ...
    def multiplier_to_scc_root(self, pos: int, /) -> _Element: ...
    def number_of_generators(self) -> int: ...
    def position(self, pt: _Point, /) -> int | _Undefined: ...
    def reserve(self, val: int, /) -> Self: ...
    def root_of_scc(self, x: _Point | int, /) -> _Point: ...
    def scc(self) -> _Gabow: ...
    def size(self) -> int: ...
    def word_graph(self) -> _WordGraph: ...

    # Runner methods are forwarded; the Python wrapper is not a Runner subclass.
    state: ClassVar[type[_Runner.state]]
    def current_state(self) -> _Runner.state: ...
    def dead(self) -> bool: ...
    def finished(self) -> bool: ...
    def kill(self) -> None: ...
    def report_why_we_stopped(self) -> None: ...
    def run(self) -> None: ...
    def run_for(self, t: timedelta, /) -> None: ...
    def run_until(self, func: Callable[[], bool], /) -> None: ...
    def running(self) -> bool: ...
    def running_for(self) -> bool: ...
    def running_until(self) -> bool: ...
    def started(self) -> bool: ...
    def stopped(self) -> bool: ...
    def stopped_by_predicate(self) -> bool: ...
    def success(self) -> bool: ...
    def timed_out(self) -> bool: ...

    # The current bindings return Reporter objects from these setters.
    def last_report(self) -> datetime: ...
    def report(self) -> bool: ...
    @overload
    def report_every(self) -> timedelta: ...
    @overload
    def report_every(self, val: timedelta, /) -> _Reporter: ...
    @overload
    def report_prefix(self) -> str: ...
    @overload
    def report_prefix(self, val: str, /) -> _Reporter: ...
    def reset_last_report(self) -> _Reporter: ...
    def reset_start_time(self) -> _Reporter: ...
    def start_time(self) -> datetime: ...

class RightAction(Action[_Element, _Point]):
    def __init__(
        self, *, generators: list[_Element] | None = None, seeds: list[_Point] | None = None
    ) -> None: ...

class LeftAction(Action[_Element, _Point]):
    def __init__(
        self,
        *args: object,
        generators: list[_Element] | None = None,
        seeds: list[_Point] | None = None,
    ) -> None: ...
