# Generated by etc/generate-stubs.py using pybind11-stubgen.
# Draft only: review signatures and incomplete types before publishing.
# AI assistance: OpenAI Codex helped implement the generator.

from __future__ import annotations

from _libsemigroups_pybind11 import (
    bmat8_col_space_basis as col_space_basis,
    bmat8_col_space_size as col_space_size,
    bmat8_is_regular_element as is_regular_element,
    bmat8_minimum_dim as minimum_dim,
    bmat8_number_of_cols as number_of_cols,
    bmat8_number_of_rows as number_of_rows,
    bmat8_one as one,
    bmat8_random as random,
    bmat8_row_space_basis as row_space_basis,
    bmat8_row_space_size as row_space_size,
    bmat8_rows as rows,
    bmat8_transpose as transpose,
)

__all__: list = [
    "col_space_basis",
    "col_space_size",
    "is_regular_element",
    "minimum_dim",
    "number_of_cols",
    "number_of_rows",
    "one",
    "random",
    "row_space_basis",
    "row_space_size",
    "rows",
    "transpose",
]
